name: example-environment
channels:
  - conda-forge
dependencies:
  - python 3.9
  - pip
  - pip:
      - h5py~=3.8.0
      - fire~=0.5.0
      - numpy~=1.23.5
      - pandas~=1.5.3
      - matplotlib~=3.7.0
      - scipy~=1.10.0
      - torch~=1.13.1
      - sympy~=1.11.1
      - numba~=0.56.4
      - pytest~=7.2.1
      - latex~=0.7.0