name: example-environment
channels:
  - conda-forge
dependencies:
  - python 3.8.5
  - pip
  - pip:
      - h5py~=2.10.0
      - fire~=0.4.0
      - numpy~=1.23.3
      - pandas~=1.2.4
      - matplotlib~=3.4.2
      - scipy~=1.9.0
      - torch~=1.12.1
      - sympy~=1.9
      - numba~=0.56.2
      - pytest~=6.2.4
